In [1]:
# 导入PyTorch,注意，实际上库的名字是torch而非PyTorch
import torch

# 数据操作

## 张量的基本操作

In [19]:
# 张量，本质是多维数组
# 一维张量对应线性代数的向量
# 二维张量对应线性代数的矩阵
# 三位及以上的张量在线性代数中没有具体名称

In [20]:
# arange()方法可以创建一个向量
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
# reshape()方法可以在不改变张量的元素值和数量的情况下改变张量形状
y = x.reshape(3,4)
y
# 也可以用-1来自动计算未指明维度的大小
# 上述reshape(3,4)可以写成reshape(-1,4)或reshape(3,-1)
z = x.reshape(-1,4)
z

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [22]:
# shape属性可以查看一个张量的形状
x.shape,y.shape

(torch.Size([12]), torch.Size([3, 4]))

In [23]:
# numel()方法可以得知一个张量的元素数量
x.numel()

12

In [24]:
# 全0或全1的张量
torch.zeros((2,3,4)),torch.ones((2,3,4))

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]))

In [25]:
# 可以通过从某个特定的概率分布中随机采样来得到张量中每个元素的值
# 比如，从均值为0、标准差为1的标准高斯分布（正态分布）中随机采样
torch.randn(3,4)

tensor([[-1.5581e+00, -1.9235e+00, -1.3834e+00, -2.8134e-01],
        [ 9.3335e-01,  3.8712e-01,  1.1518e+00,  2.4145e-01],
        [ 5.0534e-01, -1.9215e-03, -1.3502e-01,  8.4293e-02]])

In [26]:
# 也可以直接给张量中元素赋值
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

## 运算符

In [4]:
# 对于任意具有相同形状的张量，常见的标准算术运算符（+、-、*、/和**）都可以被升级为按元素运算
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [5]:
# 对输入的张量（Tensor）进行逐元素的指数运算。这里的指数运算指的是计算自然对数底数e的x次幂，即e^x
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [ ]:
# 通过逻辑运算符构建二元张量
x==y

In [ ]:
# 对张量中的所有元素进行求和，会产生一个单元素张量
x.sum()

## 广播机制

In [ ]:
# 在某些情况下，即使形状不同，可通过广播机制来执行按元素操作
# 机制如下：
# 1、通过适当复制元素来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状
# 2、对生成的数组执行按元素操作

# 在大多数情况下，将沿着数组中长度为1的轴进行广播
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a,b,a+b

## 索引和切片

In [ ]:
# 同numpy的操作，略

## 节省内存

In [ ]:
# python的id() 函数提供了内存中引用对象的确切地址
before = id(y)
y = y + x
id(y)==before

In [ ]:
# 所以，尽可能原地操作
# 使用切片表示法将操作的结果分配给先前分配的数组
z = torch.zeros_like(y)
print("id(z):",id(z))
z[:] = x + y
print("id(z):",id(z))
# 后续计算中没有重复使用X,也可以使用X[:] = X + Y或X += Y来减少操作的内存开销

## 转换为其他python对象

In [ ]:
# 深度学习定义的张量和numpy张量可相互转化，两者共享内存
X = torch.arange(12).reshape((3, -1))
A = X.numpy()
B = torch.tensor(A)
type(A),type(B)

In [ ]:
# 要将大小为1的张量转换为Python标量，我们可以调用item函数或Python的内置函数
a = torch.tensor([3.5])
a, a.item(), float(a), int (a)

## 练习

In [3]:
# p47.2
m = torch.arange(6).reshape((1,2,3))
n = torch.arange(6).reshape((3,2,1))
m + n

tensor([[[ 0,  1,  2],
         [ 4,  5,  6]],

        [[ 2,  3,  4],
         [ 6,  7,  8]],

        [[ 4,  5,  6],
         [ 8,  9, 10]]])

In [ ]:
# 广播机制遵循以下规则：

# 从后向前比较形状：从张量的最后一个维度开始，向前逐个维度比较。
# 维度兼容：如果两个张量在某个维度上的大小相等，或者其中一个张量在该维度上的大小为1，则这两个张量在该维度上是兼容的。
# 扩展维度：如果两个张量在某个维度上不兼容，则PyTorch会自动将大小为1的维度扩展为与另一个张量相同的大小。

# 数据预处理

## 读取数据集

In [11]:
import os

os.makedirs(os.path.join('..','data'),exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,Pave,127500\n')
    f.write('2,NA,10600\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [12]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN   10600
2       4.0   NaN  178100
3       NaN   NaN  140000


## 处理缺失值

In [19]:
inputs, outputs = data.iloc[:,0:2], data.iloc[:,2]
inputs = inputs.fillna(inputs.mean(numeric_only=True))
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [25]:
inputs = pd.get_dummies(inputs, dummy_na=True, dtype=int)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True
