In [2]:
# 导入PyTorch,注意，实际上库的名字是torch而非PyTorch
import torch

# 数据操作

## 张量的基本操作

In [19]:
# 张量，本质是多维数组
# 一维张量对应线性代数的向量
# 二维张量对应线性代数的矩阵
# 三位及以上的张量在线性代数中没有具体名称

In [20]:
# arange()方法可以创建一个向量
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
# reshape()方法可以在不改变张量的元素值和数量的情况下改变张量形状
y = x.reshape(3,4)
y
# 也可以用-1来自动计算未指明维度的大小
# 上述reshape(3,4)可以写成reshape(-1,4)或reshape(3,-1)
z = x.reshape(-1,4)
z

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [22]:
# shape属性可以查看一个张量的形状
x.shape,y.shape

(torch.Size([12]), torch.Size([3, 4]))

In [23]:
# numel()方法可以得知一个张量的元素数量
x.numel()

12

In [24]:
# 全0或全1的张量
torch.zeros((2,3,4)),torch.ones((2,3,4))

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]))

In [25]:
# 可以通过从某个特定的概率分布中随机采样来得到张量中每个元素的值
# 比如，从均值为0、标准差为1的标准高斯分布（正态分布）中随机采样
torch.randn(3,4)

tensor([[-1.5581e+00, -1.9235e+00, -1.3834e+00, -2.8134e-01],
        [ 9.3335e-01,  3.8712e-01,  1.1518e+00,  2.4145e-01],
        [ 5.0534e-01, -1.9215e-03, -1.3502e-01,  8.4293e-02]])

In [26]:
# 也可以直接给张量中元素赋值
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

## 运算符

In [4]:
# 对于任意具有相同形状的张量，常见的标准算术运算符（+、-、*、/和**）都可以被升级为按元素运算
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [5]:
# 对输入的张量（Tensor）进行逐元素的指数运算。这里的指数运算指的是计算自然对数底数e的x次幂，即e^x
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])