# 2.3 线性代数

# 2.3.1 标量：由只有一个元素的张量表示

In [1]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)

x+y,x-y,x*y,x/y,x**y

(tensor(5.), tensor(1.), tensor(6.), tensor(1.5000), tensor(9.))

## 2.3.2 向量：标量组成的列表，即一维张量

In [2]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [3]:
# 向量默认是列向量，使用下标xi引用向量的第i个元素
x[3]

tensor(3.)

In [4]:
# 向量的长度称为向量的维度，使用python内置函数len获取向量的维度
len(x)

4

In [5]:
# 张量只有一个轴时，我们称之为向量。也可通过shape属性来获取向量的形状
x.shape

torch.Size([4])

## 2.3.3 矩阵

In [6]:
# 当调用函数来实例化张量时，我们可以通过指定两个分量m和n来创建一个形状为m ×n的矩阵。
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [7]:
# 可以通过行索引（i）和列索引（j）来访问矩阵中的标量元素aij
A[1, 2]

tensor(6)

In [8]:
# 转置
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

## 2.3.4 张量的基本运算

In [9]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 创建A的一个副本
A, B, A + B, A * B # Hadamard积,即对应元素相乘

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]),
 tensor([[  0.,   1.,   4.,   9.],
         [ 16.,  25.,  36.,  49.],
         [ 64.,  81., 100., 121.],
         [144., 169., 196., 225.],
         [256., 289., 324., 361.]]))

In [10]:
# 将张量乘以或加上一个标量不会改变张量的形状，其中张量的每个元素都将与标量相加或相乘。
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

## 2.3.5 降维

In [11]:
# 求和
x = torch.arange(4, dtype=torch.float32)
x.sum()

tensor(6.)

In [12]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190.))

In [ ]:
# 以指定张量沿哪一个轴来通过求和降低维度
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape
# 由于输入矩阵沿0轴降维以生成输出向量，因此输入轴0的维数在输出形状中消失。

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [14]:
# 沿着行和列对矩阵求和，等价于对矩阵的所有元素进行求和。
A.sum(axis=(0, 1))

tensor(190.)

In [16]:
# 将总和除以元素总数来计算平均值
A.mean(), A.sum() / A.numel()

(tensor(9.5000), tensor(9.5000))

In [17]:
# 计算平均值的函数也可以沿指定轴降低张量的维度
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [18]:
# 调用函数来计算总和或均值时保持轴数不变会很有用
sum_A = A.sum(axis=1, keepdim=True)
sum_A, sum_A.shape

(tensor([[ 6.],
         [22.],
         [38.],
         [54.],
         [70.]]),
 torch.Size([5, 1]))

In [19]:
# 由于sum_A在对每行进行求和后仍保持两个轴，我们可以通过广播将A除以sum_A
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [20]:
# 计算A元素沿某一轴的累积总和
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

## 2.3.6 点积

In [21]:
x = torch.arange(4.0)
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)  # 点积

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [22]:
# 以通过执行按元素乘法，然后进行求和来表示两个向量的点积
torch.sum(x * y)

tensor(6.)

In [23]:
# x表示值，w表示权重，x根据w的值进行加权求和，可表示为点积x·w。
# 若权重非负且和为1，则点积可表示为加权平均值。
# 将两个向量规范化为单位向量后，点积还可表示为两个向量之间的余弦。

## 2.3.7 矩阵-向量积

In [24]:
# 调用torch.mv(A, x)时，会执行矩阵‐向量积。
# 注意，A的列维数（沿轴1的长度）必须与x的维数（其长度）相同
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
x = torch.arange(4, dtype=torch.float32)
torch.mv(A, x)

tensor([ 14.,  38.,  62.,  86., 110.])

## 2.3.8 矩阵-矩阵乘法

In [25]:
B = torch.ones(4, 3)
# 调用torch.mm(A, B)时，会执行矩阵‐矩阵乘法
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

## 2.3.9 范数

In [26]:
u = torch.tensor([3.0, -4.0])

In [27]:
# L1范数也称为曼哈顿范数或税icab范数，是向量各个元素绝对值之和
torch.norm(u, p=1), torch.abs(u).sum()

(tensor(7.), tensor(7.))

In [28]:
# L2范数也称为欧几里得范数，是向量各个元素平方和的平方根
torch.norm(u), torch.sqrt(torch.sum(u**2))

(tensor(5.), tensor(5.))

In [30]:
# Frobenius范数是矩阵元素平方和的平方根
torch.norm(torch.ones((4,9)))

tensor(6.)

# 练习

In [31]:
# p63.1
A = torch.arange(6).reshape(2,3)
(A.T).T == A

tensor([[True, True, True],
        [True, True, True]])

In [33]:
# p63.2
A = torch.arange(6).reshape(2,3)
B = torch.randn(2,3)
(A+B).T == A.T + B.T

tensor([[True, True],
        [True, True],
        [True, True]])

In [ ]:
# p63.3
# 由p63.2可知(A + A.T).T == A.T + A

In [34]:
# p63.4
X = torch.arange(24).reshape(2,3,4)
len(X)

2

In [36]:
# p63.5
Y = torch.arange(24).reshape(3,2,4)
Z = torch.arange(24).reshape(4,3,2)
len(Y), len(Z)

(3, 4)

In [ ]:
# p63.6
A = torch.arange(6).reshape(2,3)
A/A.sum(axis=1)
# 报错，因为A.sum(axis=1)的形状是(2,)，不能直接用于除法广播

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [38]:
# p63.7
X = torch.arange(24).reshape(2,3,4)
X.sum(axis=0).shape, X.sum(axis=1).shape, X.sum(axis=2).shape

(torch.Size([3, 4]), torch.Size([2, 4]), torch.Size([2, 3]))

In [46]:
# p63.8
t3d = torch.randn(2, 3, 4)
torch.linalg.norm(t3d,dim=0)

tensor([[1.7035, 2.1860, 0.8680, 0.3129],
        [1.2186, 2.3963, 1.1284, 0.1414],
        [0.6984, 1.6442, 0.1432, 0.9505]])